In [ ]:
Brief exploration of the data
* the Excel file has 4 different tabs:
* Orders:
    * Index (not consistent)
    * Order ID (unique?)
    * Order Date (bad format)
    * Ship Mode (string)
    * Custimer ID
    * Customer Name (why in orders?)
    * Origin chanel (string)
    * Country (unique value? looks all the same)
    * City
    * State
    * Postal code
    * Region
    * Catefgory
    * Sub-Category
    * Product ID
    * Sales
    * Quantity
    * Discount
    * Profit
* Campaign data
    * Order ID
    * Arrival Scan Date
    * Customer Name
* Order Process data
    * Row ID (??)
    * Order ID
    * Order Date
    * On Truck Scan Date
    * Ship Mode
* InternData Study
    * Order ID
    * Ready to Ship Date
    * Pick up Date

In [1]:
import pandas as pd

In [ ]:
# save each tab as a data frame:
# orders:
df_orders = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'Orders', header = 1)
df_orders.head(2)

,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
0,27,CA-2019-121755,2019-01-16,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049.0,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0.0,11.7741
1,45,CA-2019-118255,2019-03-11,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122.0,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0.0,19.7714

In [33]:
# save the file as .csv:
df_orders.to_csv('./data_csv/orders.csv',sep = ',', header = True, index = False)

In [16]:
df_orders.shape

(9994, 19)

In [18]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           9994 non-null   int64
 1   Order ID        9994 non-null   str
 2   Order Date      9994 non-null   datetime64[us]
 3   Ship Mode       9994 non-null   str
 4   Customer ID     9994 non-null   str
 5   Customer Name   9994 non-null   str
 6   Origin Channel  9994 non-null   str
 7   Country/Region  9994 non-null   str
 8   City            9994 non-null   str
 9   State           9994 non-null   str
 10  Postal Code     9983 non-null   float64
 11  Region          9994 non-null   str
 12  Category        9994 non-null   str
 13  Sub-Category    9994 non-null   str
 14  Product ID      9994 non-null   str
 15  Sales           9994 non-null   float64
 16  Quantity        9994 non-null   int64
 17  Discount        9994 non-null   float64
 18  Profit          9994 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(2), str(12)
memory usage: 1.4 MB

In [21]:
df_campaign = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'Campaign Data', header = 0)
df_campaign.head(2)

         Order ID Arrival Scan Date Customer Name
0  CA-2019-109666        2019-05-03  Kunst Miller
1  CA-2019-138933        2019-05-03   Jack Lebron

In [34]:
# save the file as .csv:
df_campaign.to_csv('./data_csv/campaign.csv',sep = ',', header = True, index = False)

In [22]:
df_campaign.shape

(333, 3)

In [23]:
df_campaign.info()

<class 'pandas.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    str
 1   Arrival Scan Date  333 non-null    datetime64[us]
 2   Customer Name      333 non-null    str
dtypes: datetime64[us](1), str(2)
memory usage: 7.9 KB

In [24]:
df_process = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'Order Process Data', header = 0)
df_process.head(2)

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing

In [35]:
df_process.to_csv('./data_csv/process.csv',sep = ',', header = True, index = False)

In [27]:
df_process.shape

(5899, 5)

In [28]:
df_process.info()

<class 'pandas.DataFrame'>
RangeIndex: 5899 entries, 0 to 5898
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Row ID              5899 non-null   int64
 1   Order ID            5899 non-null   str
 2   Order Date          5899 non-null   datetime64[us]
 3   On Truck Scan Date  5899 non-null   datetime64[us]
 4   Ship Mode           5899 non-null   str
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 230.6 KB

In [26]:
df_intern = pd.read_excel('data_raw_copy.xlsx',sheet_name = 'InternData Study', header = 0)
df_intern.head(2)

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03

In [36]:
df_intern.to_csv('./data_csv/intern.csv',sep = ',', header = True, index = False)

In [29]:
df_intern.shape

(290, 3)

In [30]:
df_intern.info()

<class 'pandas.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    str
 1   Ready to Ship Date  290 non-null    datetime64[us]
 2   Pickup Date         290 non-null    datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 6.9 KB