Working on the intern file

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# read the file
df_intern = pd.read_csv('./data_csv/intern.csv')

Check the file structure

In [6]:
df_intern.head()

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06

In [7]:
df_intern.shape

(290, 3)

In [8]:
df_intern.info()

<class 'pandas.DataFrame'>
RangeIndex: 290 entries, 0 to 289
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            290 non-null    str
 1   Ready to Ship Date  290 non-null    str
 2   Pickup Date         290 non-null    str
dtypes: str(3)
memory usage: 6.9 KB

In [9]:
df_intern.dtypes

Order ID              str
Ready to Ship Date    str
Pickup Date           str
dtype: object

Column names

In [10]:
df_intern.columns = df_intern.columns.str.lower()
df_intern.columns = df_intern.columns.str.replace(' ','_')

Deal with data format (surrently it is a string):

In [17]:
df_intern["ready_to_ship_date"] = pd.to_datetime(df_intern["ready_to_ship_date"])
df_intern["pickup_date"] = pd.to_datetime(df_intern["pickup_date"])

Adding new columns with year / month / day / weekday (to track the shipment and delivery info):

In [18]:
df_intern["ready_ship_year"]=df_intern["ready_to_ship_date"].dt.year
df_intern["ready_ship_month"]=df_intern["ready_to_ship_date"].dt.month
df_intern["ready_ship_weekday"]=df_intern["ready_to_ship_date"].dt.dayofweek

df_intern["pickup_year"]=df_intern["pickup_date"].dt.year
df_intern["pickup_month"]=df_intern["pickup_date"].dt.month
df_intern["pickup_weekday"]=df_intern["pickup_date"].dt.dayofweek

In [24]:
# check the result:
df_intern.head(3)

,order_id,ready_to_ship_date,pickup_date,ready_ship_year,ready_ship_month,ready_ship_weekday,pickup_year,pickup_month,pickup_weekday
0,CA-2019-116540,2019-09-02,2019-09-03,2019,9,0,2019,9,1
1,CA-2019-116540,2019-09-02,2019-09-03,2019,9,0,2019,9,1
2,CA-2019-129847,2019-09-04,2019-09-04,2019,9,2,2019,9,2

Checking for duplicates

In [25]:
# duplicates by order_id
df_intern["order_id"].duplicated().sum()
# >> 86 duplicates

np.int64(86)

In [26]:
df_intern.duplicated().sum()

np.int64(86)

In [27]:
# The duplicates we have are identical not only by the order_id but by the entire row content -> safe to drop them:
df_unique_intern = df_intern.drop_duplicates(subset="order_id", keep="first")

In [28]:
df_unique_intern.shape

(204, 9)

In [29]:
df_unique_intern.duplicated().sum()

np.int64(0)

In [30]:
df_unique_intern.to_csv('./data_csv/intern_unique.csv')

### Check the structure, types, shape, info:

In [31]:
df_unique_intern.columns

Index(['order_id', 'ready_to_ship_date', 'pickup_date', 'ready_ship_year',
       'ready_ship_month', 'ready_ship_weekday', 'pickup_year', 'pickup_month',
       'pickup_weekday'],
      dtype='str')

In [32]:
df_unique_intern.info()

<class 'pandas.DataFrame'>
Index: 204 entries, 0 to 289
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            204 non-null    str
 1   ready_to_ship_date  204 non-null    datetime64[us]
 2   pickup_date         204 non-null    datetime64[us]
 3   ready_ship_year     204 non-null    int32
 4   ready_ship_month    204 non-null    int32
 5   ready_ship_weekday  204 non-null    int32
 6   pickup_year         204 non-null    int32
 7   pickup_month        204 non-null    int32
 8   pickup_weekday      204 non-null    int32
dtypes: datetime64[us](2), int32(6), str(1)
memory usage: 11.2 KB